---
- name: Monitor OpenShift Web App
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - http://nginx-demo-route-eda-demo.apps.cluster-mztzr.mztzr.sandbox2747.opentlc.com
        delay: 5

  rules:
    - name: Web app is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Remediation on OpenShift"
          organization: "Default"

